name: segyio_basic
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - pip:
    - segyio
